automatic download and build of busybox, modernization of build system

diff --git a/zmake b/zmake
--- a/zmake
+++ b/zmake
@@ -24,6 +24,9 @@
 
 # ZShaolin system build and basic configuration
 
+QUIET=0
+DEBUG=0
+
 # configure the target
 TARGET=arm-dyne-linux-gnueabi
 # same value should be the bootstrap target
@@ -52,6 +55,7 @@ ARCH="-mfloat-abi=softfp -march=armv7-a -mtune=cortex-a8"
 PATH="$PATH:$TOOLCHAIN/bin"
 # PATH="$TOOLCHAIN/bin:$PATH"
 
+REPO="http://files.dyne.org/zshaolin/sources"
 # }}}
 
 
@@ -62,45 +66,63 @@ CXXFLAGS=$CFLAGS
 LDFLAGS="-static -static-libgcc -L$TOOLCHAIN/$TARGET/sysroot/lib -L$TOOLCHAIN/$TARGET/sysroot/usr/lib -L$PREFIX/lib -L$PREFIX/usr/lib"
 
 
+autoload colors; colors
+# standard output message routines
+# it's always useful to wrap them, in case we change behaviour later
+notice() { if [[ $QUIET == 0 ]]; then print "$fg_bold[green][*]$fg_no_bold[default] $1" >&2; fi }
+error()  { if [[ $QUIET == 0 ]]; then print "$fg[red][!]$fg[default] $1" >&2; fi }
+func()   { if [[ $DEBUG == 1 ]]; then print "$fg[blue][D]$fg[default] $1" >&2; fi }
+act()    {
+    if [[ $QUIET == 0 ]]; then
+	if [ "$1" = "-n" ]; then
+	    print -n "$fg_bold[white] . $fg_no_bold[default] $2" >&2;
+	else
+	    print "$fg_bold[white] . $fg_no_bold[default] $1" >&2;
+	fi
+    fi
+}
+
+
+
 # make sure the toolchain exists in /usr
 if ! [ -r $TOOLCHAIN/bin/$TARGET-gcc ]; then
-    echo "error: toolchain not found: $TARGET"
-    echo "first you need to bootstrap."
+    error "error: toolchain not found: $TARGET"
+    error "first you need to bootstrap."
 #    return 1
 fi
 
-echo "Compiling ZShaolin system"
-echo "Target:    $TARGET"
-echo "Toolchain: $TOOLCHAIN"
-echo "Install:   $PREFIX"
-echo "CFLAGS:    $CFLAGS"
-echo "LDFLAGS:   $LDFLAGS"
-
-echo "Command:   $@"
+notice "Compiling ZShaolin system"
+act "Target:    $TARGET"
+act "Toolchain: $TOOLCHAIN"
+act "Install:   $PREFIX"
+func "CFLAGS:    $CFLAGS"
+func "LDFLAGS:   $LDFLAGS"
+func "Command:   ${=@}"
 
 
 enter() {
     if ! [ -r $1/conf.zsh ]; then
-	echo "error: build directory misses configuration file: $1/conf.zsh"
+	error "build directory misses configuration file: $1/conf.zsh"
 	return 1
     fi
-    cd $1; echo "Entered `pwd`"
+    pushd $1
+    act "Enter `pwd`"
     shift
     source conf.zsh
-    cd -
+    popd
 }
     
 compile() {
     if [ -r $1.done ]; then
-	echo "$1.done :: already built, skipping compilation"
+	error "$1.done :: already built, skipping compilation"
 	return 1
     fi
-    echo "Compiling $1" | tee -a ../$LOGS
+    notice "Compiling $1" | tee -a ../$LOGS
     if ! [ -r $1 ]; then
-    	echo "source directory $1 not found, skipping compilation"
+    	error "source directory $1 not found, skipping compilation"
     	return 1
     fi
-    cd $1
+    pushd $1
 
     if [ -r configure ]; then
 
@@ -113,12 +135,12 @@ compile() {
 		;;
 	    *)
 		confflags="$2"
-		echo "configure = $confflags"
+		act "configure = $confflags"
 	esac
 	
 	extraflags="$3"
 	if [ "$extraflags" != "" ]; then
-	    echo "extra flags = $extraflags"
+	    act "extra flags = $extraflags"
 	fi
 
 	CC="$TARGET-gcc" AR="$TARGET-ar" RANLIB="$TARGET-ranlib" LD="$TARGET-ld" \
@@ -129,7 +151,7 @@ compile() {
 	    ./configure ${=confflags} ${=extraflags} >> ../$LOGS
 	
 	if [ $? != 0 ]; then
-	    echo "error: $1 cannot configure, skipping compilation"; cd -
+	    error "error: $1 cannot configure, skipping compilation"; cd -
 	    return 1
 	fi
 	
@@ -145,20 +167,20 @@ compile() {
 	    LDFLAGS="$LDFLAGS" \
 	    make V=1 >> ../$LOGS
 	if [ $? != 0 ]; then
-	    echo "error: $1 cannot make, aborted compilation"; cd -
+	    error "error: $1 cannot make, aborted compilation"; cd -
 	    return 1
 	fi
     fi # nomake
 
-    echo "done compiling $1"
-    cd -
+    notice "done compiling $1"
+    popd
     touch $1.done
     return 0
 }
 
 zinstall() {	
     { test ! -r $1.done } && {
-	echo "$1 not yet built, skipping installation"
+	error "$1 not yet built, skipping installation"
 	return 1 }
 
     echo "Installing $1" | tee -a ../$LOGS
@@ -166,39 +188,39 @@ zinstall() {
     PREFIX="$PREFIX" \
 	make -C $1 install >> ../$LOGS
     if [ $? != 0 ]; then
-	echo "error: $1 cannot make install, check permissions"; cd -
+	error "error: $1 cannot make install, check permissions"; cd -
 	return 1
     fi
 
-    echo "done installing $1"
+    notice "done installing $1"
     return 0
 }
 
 clean() {
     if ! [ -r $1 ]; then return 0; fi
-    echo "Cleaning $1"
+    act "Cleaning $1"
     rm -f $1.done
-    cd $1
+    pushd $1
     make clean >> ../$LOGS
-    cd - > /dev/null
+    popd
 }
 
 
 case "$1" in
     build)
-	enter build/ $@
+	enter build/ ${=@}
        	;;
     pack)
-	enter pack/ $@
+	enter pack/ ${=@}
 	;;
     clean)
-	enter build/ $@
+	enter build/ ${=@}
 	;;
     test)
 	ZHOME=$ZHOME zsh etc/zlogin
 	;;
     env)
-	echo "initializing env"
+	notice "Initializing env"
 	export ZHOME TARGET TOOLCHAIN
 	export PREFIX PATH CFLAGS
 	export CPPFLAGS CXXFLAGS LDFLAGS
@@ -208,10 +230,10 @@ case "$1" in
     source)
 	return ;;
     help|-h)
-	echo "No help. We're all on our own, for now."
+	error "No help. We're all on our own, for now."
 	;;
     *)
-	echo "Command not found: $@"
+	error "Command not found: $@"
 
 esac
 
